EXEC spAgregarPelicula 'Joker','Arthur Fleck adora hacer reír a la gente, pero su carrera como comediante es un fracaso. El repudio social, la marginación y una serie de trágicos acontecimientos lo conducen por el sendero de la locura y, finalmente, cae en el mundo del crimen.',2019,4,1,'~/ImagenesPeliculas/Joker.jpg'
EXEC spAgregarPelicula 'Soul','Un profesor de música que ha perdido la pasión se transporta fuera de su cuerpo al "Gran Antes" y debe encontrar el camino de regreso con la ayuda de un alma infantil que aprende sobre sí misma.', 2020, 3,1, '~/ImagenesPeliculas/Soul.jpg'
EXEC spAgregarPelicula 'Parasite','Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a impartir clases particulares en la adinerada casa de los Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, entablan una relación de resultados imprevisibles.', 2019, 7,1, '~/ImagenesPeliculas/Parasite.jpg'
EXEC spAgregarPelicula 'La La Land','Sebastian, un pianista de jazz, y Mia, una aspirante a actriz, se enamoran locamente; pero la ambición desmedida que tienen por triunfar en sus respectivas carreras, en una ciudad como Los Ángeles, repleta de competencia y carente de piedad, pone en peligro su amor.', 2016, 6,2, '~/ImagenesPeliculas/LaLaLand.jpg'
EXEC spAgregarPelicula 'El renacido','El trampero Hugh Glass intenta vengarse de sus compañeros, quienes lo abandonaron herido en el bosque después de que lo atacó un oso, pensando que moriría, víctima de las lesiones y de la crudeza del entorno y del invierno. Sin embargo, el rencor que siente es más fuerte que cualquier adversidad, y Glass no permitirá que nada ni nadie le prive de saciar su odio.', 2016, 2,2, '~/ImagenesPeliculas/ElRenacido.jpg'
EXEC spAgregarPelicula 'Gravity','La doctora Ryan Stone es una ingeniera médica en su primera misión espacial. Su comandante es el veterano Matt Kowalsky, en su último viaje antes de retirarse. Una caminata espacial de rutina se convierte en un desastre y la nave queda destruida, dejando a Ryan y Matt atrapados en el espacio, sin ninguna conexión con la Tierra y sin esperanza de ser rescatados. Su temor se convierte en pánico, y se dan cuenta de que su camino a casa será una aventura en el espacio.', 2013, 8,2, '~/ImagenesPeliculas/Gravity.jpg'
EXEC spAgregarPelicula 'Dolor y gloria','Salvador Mallo, un director de cine en el ocaso de su carrera, rememora su vida desde que, en la década de 1960, siendo un niño, sus padres se mudaron a Paterna, un pueblo de la provincia de Valencia, en busca de un futuro mejor.', 2019, 4,3, '~/ImagenesPeliculas/DoloryGloria.jpg'
EXEC spAgregarPelicula 'Francotirador','El francotirador y SEAL de la Armada estadounidense Chris Kyle salva muchas vidas en los campos de batalla en Irak mientras se esfuerza por ser un buen marido y padre con sus seres queridos de regreso en Estados Unidos.', 2019, 9,3, '~/ImagenesPeliculas/Francotirador.jpg'
EXEC spAgregarPelicula 'Los Miserables','Después de 19 años como prisionero, Jean Valjean es liberado por Javert, el oficial a cargo de la fuerza de trabajo de la prisión. Valjean viola su libertad y más tarde usa el dinero robado para reinventarse como alcalde y dueño de una fábrica. Por su parte, Javert promete llevar a Valjean de vuelta a la cárcel. Ocho años después, Valjean se convierte en el guardián de un niño llamado Cosette tras la muerte de su madre, pero la persecución de Javert significa que la paz tardará en llegar.', 2012, 4,3, '~/ImagenesPeliculas/LosMiserables.jpg'
EXEC spAgregarPelicula 'Ella','En Los Ángeles, un escritor desanimado desarrolla una especial relación amorosa con el sistema operativo de su computadora, una intuitiva y sensible entidad llamada Samantha.', 2013, 8,5, '~/ImagenesPeliculas/Ella.jpg'
EXEC spAgregarPelicula 'Juno','Cuando la precoz adolescente Juno MacGuff queda embarazada, ella elige a una estrella de rock fracasada y a su esposa para adoptar a su bebé nonato. Las complicaciones surgen cuando Mark, el padre elegido, empieza a ver a Juno mucho más allá que sólo la madre de su futuro hijo, poniendo en peligro a su matrimonio y la adopción.', 2008, 4,5, '~/ImagenesPeliculas/Juno.jpg'
EXEC spAgregarPelicula 'Fargo','Un vendedor de autos con problemas financieros decide secuestrar a su esposa para pedirle dinero a su suegro.', 1997, 10,5, '~/ImagenesPeliculas/Fargo.jpg'



